# RBL/DNSBL — block known spam IPs
rbls {
  spamhaus_zen {
    symbol = "RBL_SPAMHAUS_ZEN";
    rbl = "zen.spamhaus.org";
    ipv6 = true;
    returncodes {
      RBL_SPAMHAUS_SBL = "127.0.0.2";
      RBL_SPAMHAUS_CSS = "127.0.0.3";
      RBL_SPAMHAUS_XBL = "127.0.0.4/8";
      RBL_SPAMHAUS_PBL = "127.0.0.10/31";
      RBL_SPAMHAUS_DROP = "127.0.0.9";
    }
  }
  barracuda {
    symbol = "RBL_BARRACUDA";
    rbl = "b.barracudacentral.org";
  }
  spamcop {
    symbol = "RBL_SPAMCOP";
    rbl = "bl.spamcop.net";
  }
}
